src/Entity/Question.php
<?php

namespace App\Entity;

use App\Enum\AnswerStatus;
use App\Repository\AnswerRepository;
use App\Repository\QuestionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;

#[ORM\Entity(repositoryClass: QuestionRepository::class)]
#[ORM\Index(name: 'IDX_QUESTION_SLUG', columns: ['slug'], options: ['unique' => true])]
class Question
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[Gedmo\Slug(fields: ['name'])]
    #[ORM\Column(length: 255, unique: true)]
    private ?string $slug = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $question = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $askedAt = null;

    #[ORM\Column]
    private ?int $votes = 0;

    /**
     * @var Collection<int, Answer>
     */
    #[ORM\OneToMany(targetEntity: Answer::class, mappedBy: 'question', fetch: 'EXTRA_LAZY')]
    #[ORM\OrderBy(['createdAt' => 'DESC'])]
    private Collection $answers;

    public function __construct()
    {
        $this->answers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function getQuestion(): ?string
    {
        return $this->question;
    }

    public function setQuestion(string $question): static
    {
        $this->question = $question;

        return $this;
    }

    public function getAskedAt(): ?\DateTimeImmutable
    {
        return $this->askedAt;
    }

    public function setAskedAt(?\DateTimeImmutable $askedAt): static
    {
        $this->askedAt = $askedAt;

        return $this;
    }

    public function getVotes(): int
    {
        return $this->votes;
    }

    public function setVotes(int $votes): static
    {
        $this->votes = $votes;

        return $this;
    }

    public function upVotes()
    {
        $this->votes++;
    }

    public function downVotes()
    {
        $this->votes--;
    }

    public function getVotesString(): string
    {
        $votes = $this->getVotes();

        return match (true) {
            $votes > 0 => '+' . $votes,
            $votes < 0 => (string)$votes,
            default => '0',
        };
    }

    /**
     * @return Collection<int, Answer>
     */
    public function getAnswers(): Collection
    {
        return $this->answers;
    }

    public function getApprovedAnswers(): Collection
    {
        return $this->answers->matching(AnswerRepository::createApprovedCriteria());
    }



    public function addAnswer(Answer $answer): static
    {
        if (!$this->answers->contains($answer)) {
            $this->answers->add($answer);
            $answer->setQuestion($this);
        }

        return $this;
    }

    public function removeAnswer(Answer $answer): static
    {
        if ($this->answers->removeElement($answer)) {
            // set the owning side to null (unless already changed)
            if ($answer->getQuestion() === $this) {
                $answer->setQuestion(null);
            }
        }

        return $this;
    }
}

src/Controller/QuestionController.php
<?php

namespace App\Controller;

use App\Entity\Question;
use App\Repository\QuestionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Symfony\Bridge\Doctrine\Attribute\MapEntity;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Contracts\Cache\TagAwareCacheInterface;

class QuestionController extends AbstractController
{
    #[Route('/', name: 'app_homepage', methods: ['GET'])]
    public function homepage(QuestionRepository $repository): Response
    {

        return $this->render('question/homepage.html.twig', [
            'questions' => $repository->findAllAskedOrderByNewestAndNotNull()
        ]);
    }

    /**
     * @throws Exception
     */
    #[Route(path: '/questions/new', name: 'app_question_new', methods: ['GET', 'PATCH'])]
    public function new(EntityManagerInterface $entityManager, TagAwareCacheInterface $cache): Response
    {
        return new Response('This will be migrated to fixtures');
    }

    #[Route('/questions/{slug}', name: 'app_question_show', methods: ['GET'])]
    public function show(string $slug, EntityManagerInterface $entityManager): Response
    {
        $repository = $entityManager->getRepository(Question::class);
        $question = $repository->findOneBy(['slug' => $slug]);

        if (!$question) {
            throw $this->createNotFoundException('Question not found');
        }

        return $this->render('question/show.html.twig', [
            'question' => $question,
        ]);
    }

    #[Route(path: '/questions/{slug}/vote', name: 'app_question_vote', methods: ['POST'])]
    public function questionVote(
        #[MapEntity(mapping: ['slug' => 'slug'])]
        Question               $question,
        Request                $request,
        EntityManagerInterface $entityManager,
    ): Response
    {
        $direction = $request->request->get('direction');
        if ($direction === 'up') {
            $question->upVotes();
        } else if ($direction === 'down') {
            $question->downVotes();
        }

        $entityManager->flush();

        return $this->redirectToRoute('app_homepage');
    }
}

templates/question/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="jumbotron-img bg-light p-5 rounded-3">
        <div class="container">
            <h1 class="display-4">Your Questions Answered</h1>
            <p class="lead">And even answers for those questions you didn't think to ask!</p>
        </div>
    </div>
    <div class="container">
        <div class="row mb-3">
            <div class="col">
                <button class="btn btn-question">Ask a Question</button>
            </div>
        </div>
        <div class="row">
            {% for question in questions %}
                <div class="col-12 mt-4">
                    <div style="box-shadow: 2px 3px 9px 4px rgba(0,0,0,0.04);">
                        <div class="q-container p-4">
                            <div class="row">
                                <div class="col-2 text-center">
                                    <img src="{{ asset('images/tisha.png') }}" width="100" height="100"
                                         alt="Tisha avatar">
                                    <div class="mt-3">
                                        <small>
                                            {% if question.askedAt %}
                                                Asked <br>
                                                {{ question.askedAt|ago }}
                                            {% else %}
                                                (Unpublished)
                                            {% endif %}
                                        </small>
                                    </div>
                                    <form action="{{ path('app_question_vote', {slug: question.slug}) }}" method="post">
                                        <div class="vote-arrows flex-fill pt-2 js-vote-arrows" style="min-width: 90px;">
                                            <button type="submit" name="direction" value="up" class="vote-up">
                                                <i class="far fa-arrow-alt-circle-up"></i>
                                            </button>
                                            <button class="vote-down" name="direction" value="down"  type="submit">
                                                <i class="far fa-arrow-alt-circle-down"></i>
                                            </button>
                                            <span class="js-vote-total">{{ question.votesString }}</span>
                                        </div>
                                    </form>
                                </div>
                                <div class="col">
                                    <a class="q-title" href="{{ path('app_question_show', { slug: question.slug }) }}">
                                        <h2>{{ question.name }}</h2></a>
                                    <div class="q-display p-3">
                                        <i class="fa fa-quote-left me-3"></i>
                                        <p class="d-inline">{{ question.question|markdown_to_html }}</p>
                                        <p class="pt-4"><strong>--Tisha</strong></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <a class="answer-link" href="{{ path('app_question_show', {slug: question.slug}) }}"
                           style="color: #fff;">
                            <p class="q-display-response text-center p-3">
                                <i class="fa fa-magic magic-wand"></i> {{ question.answers|length }}</p>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <div>
        111
    </div>
{% endblock %}

templates/question/show.html.twig
{% extends 'base.html.twig' %}


{% block title %} Cloudfare | {{ question.name|capitalize }}{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="my-4">Question</h2>
                <div style="box-shadow: 2px 3px 9px 4px rgba(0,0,0,0.04);">
                    <div class="q-container-show p-4">
                        <div class="row">
                            <div class="col-2 text-center">
                                <img src="{{ asset('images/tisha.png') }}" width="100" height="100"  alt="Tisha avatar">
                                <div class="mt-3">
                                    <small>
                                        {% if question.askedAt %}
                                            Asked <br>
                                            {{ question.askedAt|ago }}
                                            {% else %}
                                            (Unpublished)
                                        {% endif %}
                                    </small>
                                </div>
                                <form action="{{ path('app_question_vote', {slug: question.slug}) }}" method="POST">
                                    <div class="vote-arrows flex-fill pt-2 js-vote-arrows" style="min-width: 90px;">
                                        <a class="vote-up" href="#" data-direction="up"><i class="far fa-arrow-alt-circle-up"></i></a>
                                        <a class="vote-down" href="#" data-direction="down"><i class="far fa-arrow-alt-circle-down"></i></a>
                                        <span class="js-vote-total">{{ question.votesString }}</span>
                                    </div>
                                </form>
                            </div>
                            <div class="col">
                                <h1 class="q-title-show">{{ question.name }}</h1>
                                <div class="q-display p-3">
                                    <i class="fa fa-quote-left me-3"></i>
                                    <p class="d-inline">{{ question.question|markdown_to_html }}</p>
                                    <p class="pt-4"><strong>--Tisha</strong></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="d-flex justify-content-between my-4">
            <h2 class="">Answers <span style="font-size:1.2rem;">({{ question.answers|length }})</span></h2>
            <button class="btn btn-sm btn-secondary">Submit an Answer</button>
        </div>



        <ul class="list-unstyled">
            {% include 'answer/_answer.html.twig' with { answers: question.approvedAnswers } %}
        </ul>
    </div>
{% endblock %}